import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { RouterModule } from '@angular/router';

import { AppRoutingModule } from '@src/app/app-routing.module';
import { AppComponent } from '@src/app/app.component';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { NoopAnimationsModule } from '@angular/platform-browser/animations';
import { PortfolioComponent } from '@src/app/portfolio/portfolio.component';
import { PortfolioRoutes } from '@src/app/portfolio/portfolio.routes';

import { AppModule as FuzzAppModule } from 'fuzz-demo-app';

@NgModule({
  imports: [
    RouterModule.forChild(PortfolioRoutes),
    FuzzAppModule,
    BrowserModule,
    AppRoutingModule,
    NoopAnimationsModule,
  ],
  declarations: [
    PortfolioComponent,
  ],
  providers: [],
})
export class PortfolioModule { }
