import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from '@src/app/app-routing.module';
import { AppComponent } from '@src/app/app.component';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { BarcelonaModule } from '@src/app/barcelona/barcelona.module';
import { NoopAnimationsModule } from '@angular/platform-browser/animations';

import { AppModule as FuzzAppModule } from 'fuzz-demo-app';

@NgModule({
  imports: [
    FuzzAppModule,
    BrowserModule,
    AppRoutingModule,
    BarcelonaModule,
    NoopAnimationsModule,
  ],
  declarations: [
    AppComponent,
    AutoGeneratedComponent
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
